name: super_library
description: "Highly scalable, high performance, and easy to use library for all your needs, especially made for FlutterFlow."
version: 0.0.1
homepage: https://github.com/thruthesky/super_library

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
